In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("covid_toy.csv")

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [ ]:
X_train

    age  gender  fever   cough       city
94   79    Male    NaN  Strong    Kolkata
11   65  Female   98.0    Mild     Mumbai
51   11  Female  100.0  Strong    Kolkata
79   48  Female  103.0    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
5    84  Female    NaN    Mild  Bangalore
89   46    Male  103.0  Strong  Bangalore
82   24    Male   98.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
66   51    Male  104.0    Mild    Kolkata

[80 rows x 5 columns]

In [ ]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [ ]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [ ]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']]).toarray()

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']]).toarray()

X_train_gender_city.shape

(80, 4)

In [ ]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

> age-> simple imputing since it has null values

>gender-> ordinal data->ordinal encoding

>fever-> ordinal encoding

>city-> nomial data-> One hot encoding

In [ ]:
df['age'].nunique()

55

In [ ]:
df['city'].values

array(['Kolkata', 'Delhi', 'Delhi', 'Kolkata', 'Mumbai', 'Bangalore',
       'Bangalore', 'Mumbai', 'Bangalore', 'Delhi', 'Delhi', 'Mumbai',
       'Kolkata', 'Bangalore', 'Bangalore', 'Kolkata', 'Kolkata', 'Delhi',
       'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Kolkata',
       'Delhi', 'Kolkata', 'Mumbai', 'Kolkata', 'Delhi', 'Kolkata',
       'Mumbai', 'Delhi', 'Kolkata', 'Delhi', 'Kolkata', 'Mumbai',
       'Bangalore', 'Bangalore', 'Kolkata', 'Delhi', 'Kolkata', 'Delhi',
       'Kolkata', 'Delhi', 'Bangalore', 'Delhi', 'Bangalore', 'Mumbai',
       'Bangalore', 'Bangalore', 'Mumbai', 'Delhi', 'Kolkata',
       'Bangalore', 'Delhi', 'Mumbai', 'Mumbai', 'Kolkata', 'Bangalore',
       'Mumbai', 'Kolkata', 'Bangalore', 'Mumbai', 'Bangalore',
       'Bangalore', 'Mumbai', 'Bangalore', 'Kolkata', 'Bangalore',
       'Kolkata', 'Delhi', 'Delhi', 'Delhi', 'Kolkata', 'Kolkata',
       'Delhi', 'Kolkata', 'Bangalore', 'Kolkata', 'Bangalore', 'Kolkata',
       'Mumbai', 'Delhi', 'Kolkata', 'Kolkata', 'Mumbai', 'Bangalore',
       'Bangalore', 'Bangalore', 'Kolkata', 'Bangalore', 'Delhi', 'Delhi',
       'Kolkata', 'Kolkata', 'Kolkata', 'Bangalore', 'Kolkata',
       'Bangalore', 'Mumbai', 'Kolkata'], dtype=object)

### Why Column Transformer??
till now, we had to apply different encoding techniques to our data because each column had different problems. that's why we  are now using `column transformer` which is a class of `scikit learn` library..

> through this we can literally apply diff. techniques on diff cols depening upon nature of categorical data (ordinal or nominal)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

 >`Transformers` are list of tuples -> we can have different number of tuples inside transformer since we need to apply encoding technique on 3 different columns that's why we will have to pass `3 tuples`.


> `Remainders` -> what to do with the remaining columns?

> we can do two things:
1.    passthrough -> leave them as it is
2.   drop-> delete them from the dataset

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
 ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
  ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:
transformer.transform(X_test).shape

(20, 7)