## WORKING WITH JSON DATA

In [ ]:
import pandas as pd

In [ ]:
pd.read_json('/content/test.json.zip')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

`read_json` has same features/ parameters present as that of read_csv example `nrows` ,`dtype`,`encoding`,`chunk size` etc.

### Reading json Data from a URL

In [ ]:
pd.read_json('https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json')

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
...,...,...,...,...,...
192,Kristín Sigurðardóttir,Icelandic,ZP5TBBYX6RI2UJ31,Cras dictum dolor lacinia lectus vehicula rutr...,2.80
193,Rohini Vasav,Hindi,UEFML43TCGS04KWM,"Ut accumsan, est vel fringilla varius, purus a...",9.30
194,Sunil Kapoor,Hindi,VY2A0APGVHK5NAW2,"Proin tempus eu risus nec mattis. Ut dictum, l...",8.04
195,Zamokuhle Zulu,isiZulu,XU7BX2F8M5PVZ1EF,Etiam congue dignissim volutpat. Phasellus tin...,8.39
196,Bhupesh Menon,Hindi,0CEPNRDV98KT3ORP,Maecenas tempus neque ut porttitor malesuada. ...,2.69

## WORKING WITH SQL DATA

In [ ]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /usr/local/lib/python3.12/dist-packages (2.2.9)

In [ ]:
import mysql.connector

In [ ]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [ ]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

In [ ]:
##this is not working because i dont have SQL
## in my pc will try again after installing mysql